### ISSUE TITLE
Invalid parameter ensure at init.pp:35

### ISSUE THREAD

**Issue by HanzzM** [ihrwein/puppet-syslog_ng#9]
I try to use the puppet-syslog_ng module on a RHEL6 server.
But I get the error:
 
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter ensure at /etc/puppetlabs/puppet/environments/tst/modules/syslog_ng/manifests/init.pp:35 on node test.local

Puppet version: 3.4.3 (Puppet Enterprise 3.2.3)
I downloaded from de Puppet Forge

**Comment by faxm0dem** [comment]
without answer I propose to close this issue (and the others by @HanzzM)

**Comment by ihrwein** [comment]
I agree, thanks!
